import jsPDF from 'jspdf';
import type { Grammar } from '../grammar/types';

interface ExportPdfOptions {
  title?: string;
  subtitle?: string;
  glyph?: string; // "CFG", "CNF", "GNF"
  ruleStats?: {
    startSymbol: string;
    nonTerminals: number;
    terminals: number;
  };
}

export function exportGrammarToPdf(
  grammar: Grammar,
  options: ExportPdfOptions = {}
) {
  const {
    title = 'Grammar Export',
    subtitle = 'From CNF/GNF Converter',
    glyph = 'CFG',
    ruleStats,
  } = options;

  // Create PDF with A4 page size
  const pdf = new jsPDF({
    format: 'a4',
    unit: 'mm',
    orientation: 'portrait',
  });

  // Set up colors
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  let yPos = margin;

  // Draw header bar with dark blue background
  pdf.setFillColor(31, 58, 105); // Dark blue header
  pdf.rect(0, 0, pageWidth, 30, 'F');

  // Title
  pdf.setFontSize(24);
  pdf.setTextColor(255, 255, 255); // White title
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, margin, 15);

  // Glyph badge
  pdf.setFillColor(74, 143, 255); // Accent blue
  pdf.setTextColor(255, 255, 255); // White text
  pdf.setFontSize(10);
  pdf.rect(pageWidth - 30, 8, 20, 14, 'F');
  pdf.text(glyph, pageWidth - 20, 17, { align: 'center' });

  yPos = 38;

  // Subtitle
  pdf.setFontSize(11);
  pdf.setTextColor(80, 80, 80); // Dark gray
  pdf.setFont('helvetica', 'normal');
  pdf.text(subtitle, margin, yPos);

  yPos += 12;

  // Statistics section if provided
  if (ruleStats) {
    pdf.setFillColor(245, 248, 250); // Light background
    pdf.setDrawColor(31, 58, 105); // Dark blue border
    pdf.setLineWidth(0.5);
    pdf.rect(margin, yPos - 3, pageWidth - 2 * margin, 24, 'FD');

    pdf.setFontSize(10);
    pdf.setTextColor(31, 58, 105); // Dark blue header
    pdf.setFont('helvetica', 'bold');
    pdf.text('Grammar Statistics', margin + 3, yPos + 3);

    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(40, 40, 40); // Dark text
    pdf.text(`Start Symbol: ${ruleStats.startSymbol}`, margin + 3, yPos + 10);
    pdf.text(`Non-Terminals: ${ruleStats.nonTerminals}`, margin + 3, yPos + 16);
    pdf.text(`Terminals: ${ruleStats.terminals}`, margin + 3, yPos + 22);

    yPos += 30;
  }

  // Rules section
  pdf.setFontSize(12);
  pdf.setTextColor(31, 58, 105); // Dark blue
  pdf.setFont('helvetica', 'bold');
  pdf.text('Production Rules', margin, yPos);

  yPos += 8;

  // Draw rules in monospace style with numbering
  pdf.setFontSize(9.5);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0); // Pure black

  // Draw rules in monospace style with numbering
  pdf.setFontSize(9.5);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0); // Pure black

  const lineHeight = 6.5;
  const maxLines = Math.floor((pageHeight - yPos - margin) / lineHeight);
  let lineCount = 0;

  for (let index = 0; index < grammar.productions.length; index++) {
    const rule = grammar.productions[index];
    // Format rule as "A → B | C | D"
    const head = rule.head;
    const body = rule.body.length > 0 ? rule.body.map(s => s.value).join(' | ') : 'ε';
    const ruleNum = String(index + 1).padStart(2, '0');
    const ruleLine = `${ruleNum} • ${head} → ${body}`;

    // Check if we need a new page
    if (lineCount >= maxLines) {
      pdf.addPage();
      yPos = margin;
      lineCount = 0;

      // Repeat header on new page
      pdf.setFillColor(31, 58, 105);
      pdf.rect(0, 0, pageWidth, 10, 'F');
      pdf.setFontSize(10);
      pdf.setTextColor(255, 255, 255);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Production Rules (continued)', margin, 8);
      yPos = margin + 8;
    }

    // Draw rule text
    pdf.setTextColor(0, 0, 0);
    pdf.text(ruleLine, margin + 2, yPos);
    yPos += lineHeight;
    lineCount++;
  }

  // Footer
  yPos = pageHeight - 10;
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100); // Gray footer text
  const timestamp = new Date().toLocaleString();
  pdf.text(
    `Generated by CNF/GNF Converter | ${timestamp}`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );

  return pdf;
}

/**
 * Export grammar and download as PDF file
 */
export function downloadGrammarPdf(
  grammar: Grammar,
  filename: string = 'grammar.pdf',
  options?: ExportPdfOptions
) {
  const pdf = exportGrammarToPdf(grammar, options);
  pdf.save(filename);
}

/**
 * Export comparison of two grammars (before/after transformation)
 */
export function exportComparisonToPdf(
  beforeGrammar: Grammar,
  afterGrammar: Grammar,
  transformationName: string = 'Transformation'
) {
  const pdf = new jsPDF({
    format: 'a4',
    unit: 'mm',
    orientation: 'landscape',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 12;
  const colWidth = (pageWidth - 3 * margin) / 2;

  let yPos = margin;

  // Header
  pdf.setFillColor(31, 58, 105); // Dark blue
  pdf.rect(0, 0, pageWidth, 20, 'F');

  pdf.setFontSize(18);
  pdf.setTextColor(255, 255, 255); // White text
  pdf.setFont('helvetica', 'bold');
  pdf.text(transformationName, margin, 12);

  yPos = 25;

  // Before column
  pdf.setFontSize(11);
  pdf.setTextColor(31, 58, 105); // Dark blue
  pdf.setFont('helvetica', 'bold');
  pdf.text('Input Grammar', margin, yPos);

  yPos += 7;

  // Draw before grammar
  pdf.setFontSize(8.5);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0); // Pure black

  const beforeRules = beforeGrammar.productions;
  const maxRulesPerCol = 20;

  for (let i = 0; i < Math.min(maxRulesPerCol, beforeRules.length); i++) {
    const rule = beforeRules[i];
    const body = rule.body.length > 0 ? rule.body.map(s => s.value).join(' | ') : 'ε';
    const ruleNum = String(i + 1).padStart(2, '0');
    const ruleLine = `${ruleNum} • ${rule.head} → ${body}`;
    pdf.text(ruleLine, margin + 2, yPos);
    yPos += 5;
  }

  // After column
  yPos = 25;

  pdf.setFontSize(11);
  pdf.setTextColor(31, 58, 105); // Dark blue
  pdf.setFont('helvetica', 'bold');
  pdf.text('Output Grammar', margin + colWidth + margin, yPos);

  yPos += 7;

  pdf.setFontSize(8.5);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0); // Pure black

  const afterRules = afterGrammar.productions;

  for (let i = 0; i < Math.min(maxRulesPerCol, afterRules.length); i++) {
    const rule = afterRules[i];
    const body = rule.body.length > 0 ? rule.body.map(s => s.value).join(' | ') : 'ε';
    const ruleNum = String(i + 1).padStart(2, '0');
    const ruleLine = `${ruleNum} • ${rule.head} → ${body}`;
    pdf.text(ruleLine, margin + colWidth + margin + 2, yPos);
    yPos += 5;
  }

  // Footer
  yPos = pageHeight - 8;
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100); // Gray footer text
  const timestamp = new Date().toLocaleString();
  pdf.text(
    `Generated by CNF/GNF Converter | ${timestamp}`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );

  return pdf;
}

/**
 * Download comparison PDF
 */
export function downloadComparisonPdf(
  beforeGrammar: Grammar,
  afterGrammar: Grammar,
  transformationName: string = 'Transformation',
  filename: string = 'comparison.pdf'
) {
  const pdf = exportComparisonToPdf(beforeGrammar, afterGrammar, transformationName);
  pdf.save(filename);
}
