import jsPDF from 'jspdf';
import type { Grammar } from '../grammar/types';

interface ExportPdfOptions {
  title?: string;
  subtitle?: string;
  glyph?: string;
  ruleStats?: {
    startSymbol: string;
    nonTerminals: number;
    terminals: number;
  };
}

// Helper function to sanitize text for PDF compatibility
function sanitizeForPdf(text: string): string {
  return text
    .replace(/→/g, '->')
    .replace(/ε/g, 'epsilon')
    .replace(/•/g, '-')
    .trim();
}

export function exportGrammarToPdf(
  grammar: Grammar,
  options: ExportPdfOptions = {}
) {
  const {
    title = 'Grammar Export',
    subtitle = 'From CNF/GNF Converter',
    glyph = 'CFG',
    ruleStats,
  } = options;
  const pdf = new jsPDF({
    format: 'a4',
    unit: 'mm',
    orientation: 'portrait',
  });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  let yPos = margin;
  pdf.setFillColor(31, 58, 105);
  pdf.rect(0, 0, pageWidth, 30, 'F');
  pdf.setFontSize(24);
  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, margin, 15);
  pdf.setFillColor(74, 143, 255);
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.rect(pageWidth - 30, 8, 20, 14, 'F');
  pdf.text(glyph, pageWidth - 20, 17, { align: 'center' });
  yPos = 38;
  pdf.setFontSize(11);
  pdf.setTextColor(80, 80, 80);
  pdf.setFont('helvetica', 'normal');
  pdf.text(subtitle, margin, yPos);
  yPos += 12;
  if (ruleStats) {
    pdf.setFillColor(245, 248, 250);
    pdf.setDrawColor(31, 58, 105);
    pdf.setLineWidth(0.5);
    pdf.rect(margin, yPos - 3, pageWidth - 2 * margin, 24, 'FD');
    pdf.setFontSize(10);
    pdf.setTextColor(31, 58, 105);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Grammar Statistics', margin + 3, yPos + 3);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(40, 40, 40);
    pdf.text(`Start Symbol: ${ruleStats.startSymbol}`, margin + 3, yPos + 10);
    pdf.text(`Non-Terminals: ${ruleStats.nonTerminals}`, margin + 3, yPos + 16);
    pdf.text(`Terminals: ${ruleStats.terminals}`, margin + 3, yPos + 22);
    yPos += 30;
  }
  pdf.setFontSize(12);
  pdf.setTextColor(31, 58, 105);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Production Rules', margin, yPos);
  yPos += 8;
  pdf.setFontSize(9.5);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0);
  const lineHeight = 6.5;
  const maxLines = Math.floor((pageHeight - yPos - margin) / lineHeight);
  let lineCount = 0;
  for (let index = 0; index < grammar.productions.length; index++) {
    const rule = grammar.productions[index];
    const head = rule.head;
    const body = rule.body.length > 0 ? rule.body.map(s => s.value).join(' ') : 'epsilon';
    const ruleNum = String(index + 1).padStart(2, '0');
    const ruleLine = sanitizeForPdf(`${ruleNum}. ${head} -> ${body}`);
    if (lineCount >= maxLines) {
      pdf.addPage();
      yPos = margin;
      lineCount = 0;
      pdf.setFillColor(31, 58, 105);
      pdf.rect(0, 0, pageWidth, 10, 'F');
      pdf.setFontSize(10);
      pdf.setTextColor(255, 255, 255);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Production Rules (continued)', margin, 8);
      yPos = margin + 8;
    }
    pdf.setTextColor(0, 0, 0);
    pdf.text(ruleLine, margin + 2, yPos);
    yPos += lineHeight;
    lineCount++;
  }
  yPos = pageHeight - 10;
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100);
  const timestamp = new Date().toLocaleString();
  pdf.text(
    `Generated by CNF/GNF Converter | ${timestamp}`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );
  return pdf;
}
export function downloadGrammarPdf(
  grammar: Grammar,
  filename: string = 'grammar.pdf',
  options?: ExportPdfOptions
) {
  const pdf = exportGrammarToPdf(grammar, options);
  pdf.save(filename);
}
export function exportComparisonToPdf(
  beforeGrammar: Grammar,
  afterGrammar: Grammar,
  transformationName: string = 'Transformation'
) {
  const pdf = new jsPDF({
    format: 'a4',
    unit: 'mm',
    orientation: 'landscape',
  });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 12;
  const colWidth = (pageWidth - 3 * margin) / 2;
  let yPos = margin;
  pdf.setFillColor(31, 58, 105); // Dark blue
  pdf.rect(0, 0, pageWidth, 20, 'F');
  pdf.setFontSize(18);
  pdf.setTextColor(255, 255, 255); // White text
  pdf.setFont('helvetica', 'bold');
  pdf.text(sanitizeForPdf(transformationName), margin, 12);
  yPos = 25;
  pdf.setFontSize(11);
  pdf.setTextColor(31, 58, 105); // Dark blue
  pdf.setFont('helvetica', 'bold');
  pdf.text('Input Grammar', margin, yPos);
  yPos += 7;
  pdf.setFontSize(8.5);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0); // Pure black
  const beforeRules = beforeGrammar.productions;
  const maxRulesPerCol = 20;
  for (let i = 0; i < Math.min(maxRulesPerCol, beforeRules.length); i++) {
    const rule = beforeRules[i];
    const body = rule.body.length > 0 ? rule.body.map(s => s.value).join(' ') : 'epsilon';
    const ruleNum = String(i + 1).padStart(2, '0');
    const ruleLine = sanitizeForPdf(`${ruleNum}. ${rule.head} -> ${body}`);
    pdf.text(ruleLine, margin + 2, yPos);
    yPos += 5;
  }
  yPos = 25;
  pdf.setFontSize(11);
  pdf.setTextColor(31, 58, 105); // Dark blue
  pdf.setFont('helvetica', 'bold');
  pdf.text('Output Grammar', margin + colWidth + margin, yPos);
  yPos += 7;
  pdf.setFontSize(8.5);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0); // Pure black
  const afterRules = afterGrammar.productions;
  for (let i = 0; i < Math.min(maxRulesPerCol, afterRules.length); i++) {
    const rule = afterRules[i];
    const body = rule.body.length > 0 ? rule.body.map(s => s.value).join(' ') : 'epsilon';
    const ruleNum = String(i + 1).padStart(2, '0');
    const ruleLine = sanitizeForPdf(`${ruleNum}. ${rule.head} -> ${body}`);
    pdf.text(ruleLine, margin + colWidth + margin + 2, yPos);
    yPos += 5;
  }
  yPos = pageHeight - 8;
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100); // Gray footer text
  const timestamp = new Date().toLocaleString();
  pdf.text(
    `Generated by CNF/GNF Converter | ${timestamp}`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );
  return pdf;
}
export function downloadComparisonPdf(
  beforeGrammar: Grammar,
  afterGrammar: Grammar,
  transformationName: string = 'Transformation',
  filename: string = 'comparison.pdf'
) {
  const pdf = exportComparisonToPdf(beforeGrammar, afterGrammar, transformationName);
  pdf.save(filename);
}

